# Generated by Django 4.2.7 on 2023-12-14 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='images_profile'),
        ),
    ]
