# Generated by Django 4.2.7 on 2023-12-14 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_userprofile_images'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='images',
            new_name='profile_image',
        ),
    ]
