# Generated by Django 4.2.7 on 2023-12-16 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_userprofile_address_userprofile_birth_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='pass1',
            field=models.CharField(default=1, max_length=128),
            preserve_default=False,
        ),
    ]
