# Generated by Django 4.2.7 on 2023-12-16 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_userprofile_pass1'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='pass1',
            field=models.DateField(blank=True, null=True),
        ),
    ]
