# Generated by Django 4.2.7 on 2023-12-21 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productweb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='is_available',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
