# Generated by Django 4.2.7 on 2023-12-21 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productweb', '0003_cart_cartdetail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartdetail',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='cartdetail',
            name='product',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='CartDetail',
        ),
    ]
