# Generated by Django 4.2.7 on 2023-11-26 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productweb', '0005_remove_item_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='product_images/'),
        ),
    ]
