# Generated by Django 4.2.7 on 2023-11-26 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productweb', '0009_alter_item_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='matter',
            field=models.CharField(default=2, max_length=50),
            preserve_default=False,
        ),
    ]
