# Generated by Django 4.2.7 on 2023-12-18 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productweb', '0012_remove_item_image_itemimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='matter',
            new_name='material',
        ),
    ]
