# Generated by Django 4.2.7 on 2023-12-18 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productweb', '0013_rename_matter_item_material'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='price',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
