# Generated by Django 4.2.7 on 2023-12-18 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productweb', '0015_alter_item_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.TextField(default='No description'),
        ),
    ]
